server:
  port: 6002
spring:
  application:
    name: inventory-service
  data:
    mongodb:
      ## uri: mongodb://root:generic@localhost:27017/inventorydb
      ## When the uri is not available configure as below
      host: localhost
      port: 27017
      database: inventorydb
      username: root
      password: generic
      authentication-database: admin


eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka